[wallpaper]
custom_paths = [
    "$HOME/Imagens/wallpapers",
] # List of paths to search for wallpapers

# Configuration file for HyDE
# Environment variables should be on top
# Updated config.toml file can be found at $HOME/.local/share/hyde/config.toml
